name: "Check"

on:
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  make-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Import secrets"
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "MARVEL_PUBLIC_KEY=$PUBLIC_KEY" > $HOME/marvelapp/marvel_keys.properties
          echo "MARVEL_PRIVATE_KEY=$PRIVATE_KEY" >> $HOME/marvelapp/marvel_keys.properties
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Check formatting
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
