name: "Check"

on:
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Import secrets"
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          touch marvel_keys.properties
          echo 'MARVEL_PUBLIC_KEY="$PUBLIC_KEY"' >> marvel_keys.properties
          echo 'MARVEL_PRIVATE_KEY="$PRIVATE_KEY"' >> marvel_keys.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

  check-formatting:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - name: Check formatting
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean ktlintCheck
  
  execute-testing:
    runs-on: ubuntu-latest
    needs: [prepare-env, check-formatting]
    steps:
      - name: Test - app
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :app:testProReleaseUnit

      - name: Test - characters
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :app:testProReleaseUnit

      - name: Test - core
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :app:testProReleaseUnit
